# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: emqx-sc
#   namespace: development
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "false"
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
#   fsType: ext4 
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: emqx-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: development
  labels:
    app: emqx
spec:
  replicas: 1
  serviceName: emqx
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      volumes:
      - name: emqx-data
        persistentVolumeClaim:
          claimName: emqx-pvc
      serviceAccountName: emqx
      containers:
      - name: emqx
        image: 196117091547.dkr.ecr.us-east-1.amazonaws.com/ev_pilot-dev-mqtt:latest
        resources:
          requests:
            memory: "500Mi"
            cpu: "40m"
          limits:
            memory: "700Mi"
            cpu: "80m"
        ports:
        - name: mqtt
          containerPort: 1883
        - name: mqttssl
          containerPort: 8883
        - name: mgmt
          containerPort: 8081
        - name: ws
          containerPort: 8083
        - name: wss
          containerPort: 8084
        - name: dashboard
          containerPort: 18083
        volumeMounts:
        - name: emqx-data
          mountPath: "/opt/emqx/data/mnesia"
        env:
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: "https://kubernetes.default.svc:443"
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: development
        - name: listener.ssl.external
          value: 8883
        - name: listener.ssl.external.keyfile
          value: etc/certs/emqx.key
        - name: listener.ssl.external.certfile
        - name: listener.ssl.external.cacertfile
          value: etc/certs/ca.pem
        - name: listener.ssl.external.verify
          value: verify_peer
        - name: listener.ssl.external.fail_if_no_peer_cert
          value: true

 
---
apiVersion: v1
kind: Service
metadata:
  name: emqx
  namespace: development
spec:
  type: NodePort
 # clusterIP: None
  selector:
    app: emqx
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: mqttssl
    port: 8883
    protocol: TCP
    targetPort: 8883
  - name: mgmt
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: websocket
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: wss
    port: 8084
    protocol: TCP
    targetPort: 8084
  - name: dashboard
    port: 18083
    protocol: TCP
    targetPort: 18083

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: development
data:
  EMQX_CLUSTER_DISCOVERY: "k8s"
  EMQX_CLUSTER_K8S_APP_NAME: "emqx"
  EMQX_CLUSTER_K8S_APISERVER: "https://kubernetes.default.svc:443"
  EMQX_CLUSTER_K8S_ADDRESS_TYPE: "hostname"
  EMQX_CLUSTER_K8S_SUFFIX: "svc.cluster.local"
  EMQX_CLUSTER_K8S_SERVICE_NAME: "emqx"
  EMQX_CLUSTER_K8S_NAMESPACE: "development"
  listener.ssl.external: "8883"
  listener.ssl.external.keyfile: "etc/certs/emqx.key"
  listener.ssl.external.certfile: "etc/certs/emqx.pem"
  listener.ssl.external.cacertfile: "etc/certs/ca.pem"
  listener.ssl.external.verify: "verify_peer"
  listener.ssl.external.fail_if_no_peer_cert: "true"

  
---
 apiVersion: autoscaling/v1
 kind: HorizontalPodAutoscaler
 metadata:
   name: emqx
   namespace: development
 spec:
   maxReplicas: 10
   minReplicas: 1
   scaleTargetRef:
     apiVersion: apps/v1
     kind: StatefulSet
     name: emqx
   targetCPUUtilizationPercentage: 90
 status:
   currentReplicas: 1
   desiredReplicas: 1




  








